### PR TITLE
Key is nice

### PR DESCRIPTION
**Pull request by Keyinator**
Hello. I hope you're having a great day

### CODE REVIEW

**Review by AgentBlackout — COMMENTED** [review]
amogus

**Review by Danstr5544 — APPROVED** [review]
https://user-images.githubusercontent.com/73479857/109152639-ad6cfa00-7763-11eb-92f9-4fcb6aae8350.mp4

**Comment by sirmeepington** [comment]
you want me to have a round 2 on the badge cog? :)

**Comment by Danstr5544** [comment]
Fuck off with that idea @sirmeepington

**Pull request merged**
